# Generated by Django 4.1 on 2022-09-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_student_bitiruvchi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='muallif',
            options={'ordering': ['kitob_soni']},
        ),
    ]
